<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Menu;
class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Menu::truncate();
        $menus = [
            [
                'name' => 'Dashboard',
                'url' => 'dashboard',
                'permission' => 'dashboard',
                'icon' => 'ti ti-dashboard',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Form Appointment',
                'url' => 'form-appointment',
                'permission' => 'form-appointment',
                'icon' => 'ti ti-mail',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'List Appointment',
                'url' => 'list-appointment',
                'permission' => 'list-appointment',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 2,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Form Appointment',
                'url' => 'form-appointment',
                'permission' => 'form-appointment',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 2,
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Profile Company',
                'url' => 'profile-company',
                'permission' => 'profile-company',
                'icon' => 'ti ti-building',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Profile Overview',
                'url' => 'profile-overview',
                'permission' => 'profile-overview',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 5,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Kawasan Ekonomi Khusus',
                'url' => 'kawasan-ekonomi-khusus',
                'permission' => 'kawasan-ekonomi-khusus',
                'icon' => 'ti ti-folders',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => 'PP No.71 th 2021 tentang KEK',
                'url' => 'pp-no71-2021-tentang-kek',
                'permission' => 'pp-no71-2021-tentang-kek',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 7,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Manfaat Fiskal dan Non Fiskal',
                'url' => 'manfaat-fiskal-non-fiskal',
                'permission' => 'manfaat-fiskal-non-fiskal',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 7,
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Klaster KEK Gresik - JIIPE',
                'url' => 'klaster-kek-gresik-jipe',
                'permission' => 'klaster-kek-gresik-jipe',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 7,
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Khazanah KEK Gresik',
                'url' => 'khazanah-kek-gresik',
                'permission' => 'khazanah-kek-gresik',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 7,
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => 'Kawasan',
                'url' => 'kawasan',
                'permission' => 'kawasan',
                'icon' => 'ti ti-map',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => 'Kawasan Overview',
                'url' => 'kawasan-overview',
                'permission' => 'kawasan-overview',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 12,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'View List Kawasan',
                'url' => 'view-list-kawasan',
                'permission' => 'view-list-kawasan',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 12,
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Artikel & Berita',
                'url' => 'artikel-berita',
                'permission' => 'artikel-berita',
                'icon' => 'ti ti-news',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 6,
                'is_active' => 1,
            ],
            [
                'name' => 'Blog Overview',
                'url' => 'blog-overview',
                'permission' => 'blog-overview',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 15,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Gallery',
                'url' => 'gallery',
                'permission' => 'gallery',
                'icon' => 'ti ti-photo',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 7,
                'is_active' => 1,
            ],
            [
                'name' => 'Gallery Overview',
                'url' => 'gallery-overview',
                'permission' => 'gallery-overview',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 17,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Brochures',
                'url' => 'brochures',
                'permission' => 'brochures',
                'icon' => 'ti ti-file',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 8,
                'is_active' => 1,
            ],
            [
                'name' => 'Brochures Overview',
                'url' => 'brochures-overview',
                'permission' => 'brochures-overview',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 19,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Contact',
                'url' => 'contact',
                'permission' => 'contact',
                'icon' => 'ti ti-phone',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 9,
                'is_active' => 1,
            ],
            [
                'name' => 'Contact Overview',
                'url' => 'contact-overview',
                'permission' => 'contact-overview',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 21,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Contact Email',
                'url' => 'contact-email',
                'permission' => 'contact-email',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 21,
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Brochures Email',
                'url' => 'brochures-email',
                'permission' => 'brochures-email',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 21,
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Career',
                'url' => 'career',
                'permission' => 'career',
                'icon' => 'ti ti-briefcase',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 10,
                'is_active' => 1,
            ],
            [
                'name' => 'Career Static',
                'url' => 'career-static',
                'permission' => 'career-static',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 25,
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Career List',
                'url' => 'career-list',
                'permission' => 'career-list',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 25,
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Career Enquire',
                'url' => 'career-enquire',
                'permission' => 'career-enquire',
                'icon' => '#',
                'type' => 'admin_side',
                'parent_id' => 25,
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'General Setting',
                'url' => 'general-setting',
                'permission' => 'general-setting',
                'icon' => 'ti ti-settings',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 11,
                'is_active' => 1,
            ],
            [
                'name' => 'Language (Bahasa)',
                'url' => 'language-bahasa',
                'permission' => 'language-bahasa',
                'icon' => 'ti ti-language',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 12,
                'is_active' => 1,
            ],
            [
                'name' => 'Logout',
                'url' => 'logout',
                'permission' => 'logout',
                'icon' => 'ti ti-logout',
                'type' => 'admin_side',
                'parent_id' => null,
                'order' => 13,
                'is_active' => 1,
            ],
        ];

        foreach ($menus as $menu) {
            Menu::create($menu);
        }
    }
}
