<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Models\SubResourceEnergy;
use App\Models\SubResourceEnergyTranslation;
class SubResourceEnergySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        SubResourceEnergy::truncate();
        SubResourceEnergyTranslation::truncate();

        $now = Carbon::now();

        // Data untuk Zone ID 5
        $energiesZone5 = [
            [
                'id' => 1,
                'zone_id' => 5,
                'image' => null,
                'icon' => 'thumb_27020-power-plant_adaptiveResize_59_59.png',
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Pembangkit Listrik',
                        'subtitle' => 'Gas Power Plant',
                        'description' => 'Pembangkit listrik tenaga gas dengan sistem siklus gabungan, efisien dan fleksibel dengan emisi rendah dalam meminimalkan dampak lingkungan dan memberikan kualitas terbaik.',
                        'specifications' => '<ul><li><strong>Listrik</strong><br>PHASE 1 – 23 MW Dual Fuel Power Plant (Gas & liquid fuel oil)</li></ul><p><strong>PHASE 2:</strong></p><p>- 250 MW Dual source, Dual feeder (Will be ready in 2023)</p><p>- 250 MW Dual source, Dual feeder (Will be ready in 2025)</p><p><strong>PHASE 3</strong> – 660 MW</p><ul><li><strong>Gas</strong><br>PHASE 1 – Capacity up to 85 MMSCFD</li></ul>',
                        'meta_title' => 'Pembangkit Listrik - JIIPE',
                        'meta_description' => 'Pembangkit listrik tenaga gas dengan sistem siklus gabungan, kapasitas hingga 660 MW',
                        'meta_keywords' => 'pembangkit listrik, power plant, gas, dual fuel, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Power Plant',
                        'subtitle' => 'Gas Power Plant',
                        'description' => 'Gas power plant with combined cycle system, efficient and flexible with low emission in minimizing the environmental impact and giving the best quality.',
                        'specifications' => '<ul><li><strong>Electricity</strong><br>PHASE 1 – 23 MW Dual Fuel Power Plant (Gas & liquid fuel oil)</li></ul><p><strong>PHASE 2:</strong></p><p>- 250 MW Dual source, Dual feeder (Will be ready in 2023)</p><p>- 250 MW Dual source, Dual feeder (Will be ready in 2025)</p><p><strong>PHASE 3</strong> – 660 MW</p><ul><li><strong>Gas</strong><br>PHASE 1 – Capacity up to 85 MMSCFD</li></ul>',
                        'meta_title' => 'Power Plant - JIIPE',
                        'meta_description' => 'Gas power plant with combined cycle system, capacity up to 660 MW',
                        'meta_keywords' => 'power plant, gas, dual fuel, electricity, JIIPE',
                    ],
                    'zh' => [
                        'name' => '发电厂',
                        'subtitle' => '燃气发电厂',
                        'description' => '燃气发电厂采用联合循环系统，高效灵活，低排放，最大限度地减少环境影响并提供最佳质量。',
                        'specifications' => '<ul><li><strong>电力</strong><br>第1阶段 – 23 MW双燃料发电厂（燃气和液体燃料油）</li></ul><p><strong>第2阶段：</strong></p><p>- 250 MW双源，双馈线（将于2023年准备就绪）</p><p>- 250 MW双源，双馈线（将于2025年准备就绪）</p><p><strong>第3阶段</strong> – 660 MW</p><ul><li><strong>燃气</strong><br>第1阶段 – 容量高达85 MMSCFD</li></ul>',
                        'meta_title' => '发电厂 - JIIPE',
                        'meta_description' => '燃气发电厂采用联合循环系统，容量高达660 MW',
                        'meta_keywords' => '发电厂, 燃气, 双燃料, 电力, JIIPE',
                    ],
                    'ja' => [
                        'name' => '発電所',
                        'subtitle' => 'ガス発電所',
                        'description' => 'コンバインドサイクルシステムを備えたガス発電所で、効率的で柔軟性があり、低排出で環境への影響を最小限に抑え、最高の品質を提供します。',
                        'specifications' => '<ul><li><strong>電力</strong><br>フェーズ1 – 23 MWデュアル燃料発電所（ガスと液体燃料油）</li></ul><p><strong>フェーズ2：</strong></p><p>- 250 MWデュアルソース、デュアルフィーダー（2023年に準備完了予定）</p><p>- 250 MWデュアルソース、デュアルフィーダー（2025年に準備完了予定）</p><p><strong>フェーズ3</strong> – 660 MW</p><ul><li><strong>ガス</strong><br>フェーズ1 – 容量最大85 MMSCFD</li></ul>',
                        'meta_title' => '発電所 - JIIPE',
                        'meta_description' => 'コンバインドサイクルシステムを備えたガス発電所、容量最大660 MW',
                        'meta_keywords' => '発電所, ガス, デュアル燃料, 電力, JIIPE',
                    ],
                    'ko' => [
                        'name' => '발전소',
                        'subtitle' => '가스 발전소',
                        'description' => '복합 사이클 시스템을 갖춘 가스 발전소로 효율적이고 유연하며 저배출로 환경 영향을 최소화하고 최고의 품질을 제공합니다.',
                        'specifications' => '<ul><li><strong>전력</strong><br>1단계 – 23 MW 이중 연료 발전소（가스 및 액체 연료유）</li></ul><p><strong>2단계：</strong></p><p>- 250 MW 이중 소스, 이중 피더（2023년 준비 완료 예정）</p><p>- 250 MW 이중 소스, 이중 피더（2025년 준비 완료 예정）</p><p><strong>3단계</strong> – 660 MW</p><ul><li><strong>가스</strong><br>1단계 – 용량 최대 85 MMSCFD</li></ul>',
                        'meta_title' => '발전소 - JIIPE',
                        'meta_description' => '복합 사이클 시스템을 갖춘 가스 발전소, 용량 최대 660 MW',
                        'meta_keywords' => '발전소, 가스, 이중 연료, 전력, JIIPE',
                    ],
                    'tw' => [
                        'name' => '發電廠',
                        'subtitle' => '燃氣發電廠',
                        'description' => '燃氣發電廠採用聯合循環系統，高效靈活，低排放，最大限度地減少環境影響並提供最佳質量。',
                        'specifications' => '<ul><li><strong>電力</strong><br>第1階段 – 23 MW雙燃料發電廠（燃氣和液體燃料油）</li></ul><p><strong>第2階段：</strong></p><p>- 250 MW雙源，雙饋線（將於2023年準備就緒）</p><p>- 250 MW雙源，雙饋線（將於2025年準備就緒）</p><p><strong>第3階段</strong> – 660 MW</p><ul><li><strong>燃氣</strong><br>第1階段 – 容量高達85 MMSCFD</li></ul>',
                        'meta_title' => '發電廠 - JIIPE',
                        'meta_description' => '燃氣發電廠採用聯合循環系統，容量高達660 MW',
                        'meta_keywords' => '發電廠, 燃氣, 雙燃料, 電力, JIIPE',
                    ],
                ],
            ],
            [
                'id' => 2,
                'zone_id' => 5,
                'image' => null,
                'icon' => 'thumb_4f454-water_adaptiveResize_59_59.png',
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Instalasi Pengolahan Air',
                        'subtitle' => 'Water Treatment Plant',
                        'description' => 'Kami menyediakan air industri dengan peralatan, sistem, dan layanan terbaik untuk meningkatkan keandalan operasional Anda, mengurangi biaya produksi Anda dan mendukung kepatuhan lingkungan.',
                        'specifications' => '<ul><li><strong>Phase 1:</strong></li></ul><p style="margin-left: 40px">- 100 m3/hour / (2400 m3/day) – Sea Water Reverse Osmosis (SWRO) facility</p><p style="margin-left: 40px">- 1500 m3/day from BWRO facility (Recycle)</p><ul><li><strong>Phase 2:</strong></li></ul><p style="margin-left: 40px">- 600 lps or 2160 m3/hour (51840 m3/day)</p><ul><li><strong>Phase 3:</strong></li></ul><p style="margin-left: 40px">- 1000 lps (86,400 m3/day)</p>',
                        'meta_title' => 'Instalasi Pengolahan Air - JIIPE',
                        'meta_description' => 'Instalasi pengolahan air dengan teknologi SWRO dan BWRO, kapasitas hingga 86,400 m3/day',
                        'meta_keywords' => 'pengolahan air, water treatment, SWRO, BWRO, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Water Treatment Plant',
                        'subtitle' => 'Industrial Water Supply',
                        'description' => 'We supply industrial water with best equipment, system and service to improve your operational reliability, reduce your production cost and support environmental compliance.',
                        'specifications' => '<ul><li><strong>Phase 1:</strong></li></ul><p style="margin-left: 40px">- 100 m3/hour / (2400 m3/day) – Sea Water Reverse Osmosis (SWRO) facility</p><p style="margin-left: 40px">- 1500 m3/day from BWRO facility (Recycle)</p><ul><li><strong>Phase 2:</strong></li></ul><p style="margin-left: 40px">- 600 lps or 2160 m3/hour (51840 m3/day)</p><ul><li><strong>Phase 3:</strong></li></ul><p style="margin-left: 40px">- 1000 lps (86,400 m3/day)</p>',
                        'meta_title' => 'Water Treatment Plant - JIIPE',
                        'meta_description' => 'Water treatment plant with SWRO and BWRO technology, capacity up to 86,400 m3/day',
                        'meta_keywords' => 'water treatment, SWRO, BWRO, industrial water, JIIPE',
                    ],
                    'zh' => [
                        'name' => '水处理厂',
                        'subtitle' => '工业供水',
                        'description' => '我们提供工业用水，配备最佳设备、系统和服务，以提高您的运营可靠性，降低生产成本并支持环境合规。',
                        'specifications' => '<ul><li><strong>第1阶段：</strong></li></ul><p style="margin-left: 40px">- 100 m3/小时 / (2400 m3/天) – 海水反渗透（SWRO）设施</p><p style="margin-left: 40px">- 1500 m3/天来自BWRO设施（回收）</p><ul><li><strong>第2阶段：</strong></li></ul><p style="margin-left: 40px">- 600升/秒或2160 m3/小时（51840 m3/天）</p><ul><li><strong>第3阶段：</strong></li></ul><p style="margin-left: 40px">- 1000升/秒（86,400 m3/天）</p>',
                        'meta_title' => '水处理厂 - JIIPE',
                        'meta_description' => '水处理厂采用SWRO和BWRO技术，容量高达86,400 m3/天',
                        'meta_keywords' => '水处理, SWRO, BWRO, 工业用水, JIIPE',
                    ],
                    'ja' => [
                        'name' => '水処理プラント',
                        'subtitle' => '工業用水供給',
                        'description' => '最高の機器、システム、サービスを備えた工業用水を供給し、運用の信頼性を向上させ、生産コストを削減し、環境コンプライアンスをサポートします。',
                        'specifications' => '<ul><li><strong>フェーズ1：</strong></li></ul><p style="margin-left: 40px">- 100 m3/時間 / (2400 m3/日) – 海水逆浸透（SWRO）施設</p><p style="margin-left: 40px">- BWRO施設から1500 m3/日（リサイクル）</p><ul><li><strong>フェーズ2：</strong></li></ul><p style="margin-left: 40px">- 600リットル/秒または2160 m3/時間（51840 m3/日）</p><ul><li><strong>フェーズ3：</strong></li></ul><p style="margin-left: 40px">- 1000リットル/秒（86,400 m3/日）</p>',
                        'meta_title' => '水処理プラント - JIIPE',
                        'meta_description' => 'SWROおよびBWRO技術を備えた水処理プラント、容量最大86,400 m3/日',
                        'meta_keywords' => '水処理, SWRO, BWRO, 工業用水, JIIPE',
                    ],
                    'ko' => [
                        'name' => '수처리 플랜트',
                        'subtitle' => '산업용수 공급',
                        'description' => '최고의 장비, 시스템 및 서비스를 갖춘 산업용수를 공급하여 운영 신뢰성을 향상시키고 생산 비용을 절감하며 환경 규정 준수를 지원합니다.',
                        'specifications' => '<ul><li><strong>1단계：</strong></li></ul><p style="margin-left: 40px">- 100 m3/시간 / (2400 m3/일) – 해수 역삼투（SWRO）시설</p><p style="margin-left: 40px">- BWRO 시설에서 1500 m3/일（재활용）</p><ul><li><strong>2단계：</strong></li></ul><p style="margin-left: 40px">- 600리터/초 또는 2160 m3/시간（51840 m3/일）</p><ul><li><strong>3단계：</strong></li></ul><p style="margin-left: 40px">- 1000리터/초（86,400 m3/일）</p>',
                        'meta_title' => '수처리 플랜트 - JIIPE',
                        'meta_description' => 'SWRO 및 BWRO 기술을 갖춘 수처리 플랜트, 용량 최대 86,400 m3/일',
                        'meta_keywords' => '수처리, SWRO, BWRO, 산업용수, JIIPE',
                    ],
                    'tw' => [
                        'name' => '水處理廠',
                        'subtitle' => '工業供水',
                        'description' => '我們提供工業用水，配備最佳設備、系統和服務，以提高您的運營可靠性，降低生產成本並支持環境合規。',
                        'specifications' => '<ul><li><strong>第1階段：</strong></li></ul><p style="margin-left: 40px">- 100 m3/小時 / (2400 m3/天) – 海水反滲透（SWRO）設施</p><p style="margin-left: 40px">- 1500 m3/天來自BWRO設施（回收）</p><ul><li><strong>第2階段：</strong></li></ul><p style="margin-left: 40px">- 600升/秒或2160 m3/小時（51840 m3/天）</p><ul><li><strong>第3階段：</strong></li></ul><p style="margin-left: 40px">- 1000升/秒（86,400 m3/天）</p>',
                        'meta_title' => '水處理廠 - JIIPE',
                        'meta_description' => '水處理廠採用SWRO和BWRO技術，容量高達86,400 m3/天',
                        'meta_keywords' => '水處理, SWRO, BWRO, 工業用水, JIIPE',
                    ],
                ],
            ],
            [
                'id' => 3,
                'zone_id' => 5,
                'image' => null,
                'icon' => 'thumb_bcb96-waste_adaptiveResize_59_59.png',
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Instalasi Pengolahan Air Limbah',
                        'subtitle' => 'Waste Water Treatment Plant',
                        'description' => 'Fasilitas instalasi pengolahan air limbah dengan teknologi canggih (MBR)',
                        'specifications' => '<ul><li><strong>PHASE 1:</strong> 2500 m3/day (MBR Technology)</li></ul>',
                        'meta_title' => 'Instalasi Pengolahan Air Limbah - JIIPE',
                        'meta_description' => 'Instalasi pengolahan air limbah dengan teknologi MBR, kapasitas 2500 m3/day',
                        'meta_keywords' => 'pengolahan air limbah, waste water treatment, MBR, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Waste Water Treatment Plant',
                        'subtitle' => 'Advanced Technology Treatment',
                        'description' => 'Advanced technology (MBR) Waste Water treatment plant facilities',
                        'specifications' => '<ul><li><strong>PHASE 1:</strong> 2500 m3/day (MBR Technology)</li></ul>',
                        'meta_title' => 'Waste Water Treatment Plant - JIIPE',
                        'meta_description' => 'Waste water treatment plant with MBR technology, capacity 2500 m3/day',
                        'meta_keywords' => 'waste water treatment, MBR, wastewater, JIIPE',
                    ],
                    'zh' => [
                        'name' => '废水处理厂',
                        'subtitle' => '先进技术处理',
                        'description' => '先进技术（MBR）废水处理厂设施',
                        'specifications' => '<ul><li><strong>第1阶段：</strong> 2500 m3/天（MBR技术）</li></ul>',
                        'meta_title' => '废水处理厂 - JIIPE',
                        'meta_description' => '废水处理厂采用MBR技术，容量2500 m3/天',
                        'meta_keywords' => '废水处理, MBR, 污水, JIIPE',
                    ],
                    'ja' => [
                        'name' => '廃水処理プラント',
                        'subtitle' => '先進技術処理',
                        'description' => '先進技術（MBR）廃水処理プラント施設',
                        'specifications' => '<ul><li><strong>フェーズ1：</strong> 2500 m3/日（MBR技術）</li></ul>',
                        'meta_title' => '廃水処理プラント - JIIPE',
                        'meta_description' => 'MBR技術を備えた廃水処理プラント、容量2500 m3/日',
                        'meta_keywords' => '廃水処理, MBR, 排水, JIIPE',
                    ],
                    'ko' => [
                        'name' => '폐수 처리 플랜트',
                        'subtitle' => '첨단 기술 처리',
                        'description' => '첨단 기술（MBR）폐수 처리 플랜트 시설',
                        'specifications' => '<ul><li><strong>1단계：</strong> 2500 m3/일（MBR 기술）</li></ul>',
                        'meta_title' => '폐수 처리 플랜트 - JIIPE',
                        'meta_description' => 'MBR 기술을 갖춘 폐수 처리 플랜트, 용량 2500 m3/일',
                        'meta_keywords' => '폐수 처리, MBR, 하수, JIIPE',
                    ],
                    'tw' => [
                        'name' => '廢水處理廠',
                        'subtitle' => '先進技術處理',
                        'description' => '先進技術（MBR）廢水處理廠設施',
                        'specifications' => '<ul><li><strong>第1階段：</strong> 2500 m3/天（MBR技術）</li></ul>',
                        'meta_title' => '廢水處理廠 - JIIPE',
                        'meta_description' => '廢水處理廠採用MBR技術，容量2500 m3/天',
                        'meta_keywords' => '廢水處理, MBR, 污水, JIIPE',
                    ],
                ],
            ],
        ];

        // Data untuk Zone ID 6
        $energiesZone6 = [
            [
                'id' => 4,
                'zone_id' => 6,
                'image' => null,
                'icon' => 'thumb_7347e-plant_adaptiveResize_59_59.png',
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Pembangkit Listrik',
                        'subtitle' => 'Pembangkit Listrik Tenaga Gas dan Batubara',
                        'description' => 'Pembangkit Listrik Tenaga Gas dan Batubara dengan sistem siklus gabungan, efektif dan fleksibel dengan emisi rendah dalam meminimalkan dampak lingkungan dan solusi optimal.',
                        'specifications' => '<ul><li><strong>Listrik</strong><br>FASE 1 - 3 x 7,65 MW DUAL FUEL POWER PLANT disediakan dan EPC oleh Wärtsilä, Finland. Terletak di Blok E.</li><li><strong>Gas</strong><br>FASE 1 - pipa gas di Blok E (6"), Daendels ke Underpass Road (16") dan dari Pipa PGN (24") di Jalan Daendels.</li></ul>',
                        'meta_title' => 'Pembangkit Listrik - JIIPE Port',
                        'meta_description' => 'Pembangkit listrik tenaga gas dan batubara dengan sistem siklus gabungan, 3 x 7,65 MW',
                        'meta_keywords' => 'pembangkit listrik, power plant, gas, batubara, dual fuel, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Power Plant',
                        'subtitle' => 'Gas and Coal Power Plant',
                        'description' => 'Gas and Coal Power Plant with combined cycle system, effective and flexible with low emission in minimizing environmental impact and optimal solution.',
                        'specifications' => '<ul><li><strong>Electricity</strong><br>PHASE 1 - 3 x 7.65 MW DUAL FUEL POWER PLANT provided and EPC by Wärtsilä, Finland. Located in Block E.</li><li><strong>Gas</strong><br>PHASE 1 - gas pipe in Block E (6"), Daendels to Underpass Road (16") and from PGN Pipe (24") on Daendels Road.</li></ul>',
                        'meta_title' => 'Power Plant - JIIPE Port',
                        'meta_description' => 'Gas and coal power plant with combined cycle system, 3 x 7.65 MW',
                        'meta_keywords' => 'power plant, gas, coal, dual fuel, JIIPE',
                    ],
                    'zh' => [
                        'name' => '发电厂',
                        'subtitle' => '燃气和煤炭发电厂',
                        'description' => '燃气和煤炭发电厂采用联合循环系统，高效灵活，低排放，最大限度地减少环境影响和优化解决方案。',
                        'specifications' => '<ul><li><strong>电力</strong><br>第1阶段 - 3 x 7.65 MW双燃料发电厂，由芬兰Wärtsilä提供和EPC。位于E区。</li><li><strong>燃气</strong><br>第1阶段 - E区燃气管道（6英寸），Daendels到地下通道（16英寸）和Daendels路上的PGN管道（24英寸）。</li></ul>',
                        'meta_title' => '发电厂 - JIIPE港口',
                        'meta_description' => '燃气和煤炭发电厂采用联合循环系统，3 x 7.65 MW',
                        'meta_keywords' => '发电厂, 燃气, 煤炭, 双燃料, JIIPE',
                    ],
                    'ja' => [
                        'name' => '発電所',
                        'subtitle' => 'ガスおよび石炭発電所',
                        'description' => 'ガスおよび石炭発電所で、コンバインドサイクルシステムを備え、効果的で柔軟性があり、低排出で環境への影響を最小限に抑え、最適なソリューションを提供します。',
                        'specifications' => '<ul><li><strong>電力</strong><br>フェーズ1 - 3 x 7.65 MWデュアル燃料発電所、フィンランドのWärtsiläによって提供およびEPC。ブロックEに位置。</li><li><strong>ガス</strong><br>フェーズ1 - ブロックEのガスパイプ（6インチ），DaendelsからUnderpass Road（16インチ）およびDaendels RoadのPGNパイプ（24インチ）。</li></ul>',
                        'meta_title' => '発電所 - JIIPE港',
                        'meta_description' => 'ガスおよび石炭発電所で、コンバインドサイクルシステムを備え、3 x 7.65 MW',
                        'meta_keywords' => '発電所, ガス, 石炭, デュアル燃料, JIIPE',
                    ],
                    'ko' => [
                        'name' => '발전소',
                        'subtitle' => '가스 및 석탄 발전소',
                        'description' => '가스 및 석탄 발전소로 복합 사이클 시스템을 갖추고 있으며, 효과적이고 유연하며 저배출로 환경 영향을 최소화하고 최적의 솔루션을 제공합니다.',
                        'specifications' => '<ul><li><strong>전력</strong><br>1단계 - 3 x 7.65 MW 이중 연료 발전소, 핀란드 Wärtsilä에서 제공 및 EPC. E블록에 위치.</li><li><strong>가스</strong><br>1단계 - E블록의 가스 파이프（6인치），Daendels에서 지하도로（16인치）및 Daendels 도로의 PGN 파이프（24인치）.</li></ul>',
                        'meta_title' => '발전소 - JIIPE 항구',
                        'meta_description' => '가스 및 석탄 발전소로 복합 사이클 시스템을 갖춤, 3 x 7.65 MW',
                        'meta_keywords' => '발전소, 가스, 석탄, 이중 연료, JIIPE',
                    ],
                    'tw' => [
                        'name' => '發電廠',
                        'subtitle' => '燃氣和煤炭發電廠',
                        'description' => '燃氣和煤炭發電廠採用聯合循環系統，高效靈活，低排放，最大限度地減少環境影響和優化解決方案。',
                        'specifications' => '<ul><li><strong>電力</strong><br>第1階段 - 3 x 7.65 MW雙燃料發電廠，由芬蘭Wärtsilä提供和EPC。位於E區。</li><li><strong>燃氣</strong><br>第1階段 - E區燃氣管道（6英寸），Daendels到地下通道（16英寸）和Daendels路上的PGN管道（24英寸）。</li></ul>',
                        'meta_title' => '發電廠 - JIIPE港口',
                        'meta_description' => '燃氣和煤炭發電廠採用聯合循環系統，3 x 7.65 MW',
                        'meta_keywords' => '發電廠, 燃氣, 煤炭, 雙燃料, JIIPE',
                    ],
                ],
            ],
            [
                'id' => 5,
                'zone_id' => 6,
                'image' => null,
                'icon' => 'thumb_5fa64-water-1_adaptiveResize_59_59.png',
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Instalasi Pengolahan Air',
                        'subtitle' => 'Water Treatment Plant',
                        'description' => 'Kami menyediakan air industri dengan peralatan, sistem, dan layanan terbaik untuk meningkatkan keandalan operasional Anda, mengurangi biaya produksi Anda dan mendukung kepatuhan lingkungan.',
                        'specifications' => '<ul><li>FASE 1 - Tangki Air Tanah (GWT) kapasitas 1.000 m3.</li><li>7 kolam penampungan air dengan total 42 ha juga sebagai pengumpulan air hujan.</li></ul>',
                        'meta_title' => 'Instalasi Pengolahan Air - JIIPE Port',
                        'meta_description' => 'Instalasi pengolahan air dengan tangki 1.000 m3 dan 7 kolam penampungan 42 ha',
                        'meta_keywords' => 'pengolahan air, water treatment, tangki air, kolam penampungan, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Water Treatment Plant',
                        'subtitle' => 'Industrial Water Supply',
                        'description' => 'We supply industrial water with best equipment, system, and service to improve your operational reliability, reduce your production cost and support environmental compliance.',
                        'specifications' => '<ul><li>PHASE 1 - Ground Water Tank (GWT) capacity 1,000 m3.</li><li>7 water retention ponds with a total of 42 ha also as rainwater collection.</li></ul>',
                        'meta_title' => 'Water Treatment Plant - JIIPE Port',
                        'meta_description' => 'Water treatment plant with 1,000 m3 tank and 7 retention ponds 42 ha',
                        'meta_keywords' => 'water treatment, water tank, retention ponds, JIIPE',
                    ],
                    'zh' => [
                        'name' => '水处理厂',
                        'subtitle' => '工业供水',
                        'description' => '我们提供工业用水，配备最佳设备、系统和服务，以提高您的运营可靠性，降低生产成本并支持环境合规。',
                        'specifications' => '<ul><li>第1阶段 - 地下水箱（GWT）容量1,000 m3。</li><li>7个蓄水池，总面积42公顷，也用作雨水收集。</li></ul>',
                        'meta_title' => '水处理厂 - JIIPE港口',
                        'meta_description' => '水处理厂配备1,000 m3水箱和7个42公顷蓄水池',
                        'meta_keywords' => '水处理, 水箱, 蓄水池, JIIPE',
                    ],
                    'ja' => [
                        'name' => '水処理プラント',
                        'subtitle' => '工業用水供給',
                        'description' => '最高の機器、システム、サービスを備えた工業用水を供給し、運用の信頼性を向上させ、生産コストを削減し、環境コンプライアンスをサポートします。',
                        'specifications' => '<ul><li>フェーズ1 - 地下水タンク（GWT）容量1,000 m3。</li><li>合計42ヘクタールの7つの貯水池で、雨水収集としても機能。</li></ul>',
                        'meta_title' => '水処理プラント - JIIPE港',
                        'meta_description' => '1,000 m3タンクと7つの42ヘクタール貯水池を備えた水処理プラント',
                        'meta_keywords' => '水処理, 水タンク, 貯水池, JIIPE',
                    ],
                    'ko' => [
                        'name' => '수처리 플랜트',
                        'subtitle' => '산업용수 공급',
                        'description' => '최고의 장비, 시스템 및 서비스를 갖춘 산업용수를 공급하여 운영 신뢰성을 향상시키고 생산 비용을 절감하며 환경 규정 준수를 지원합니다.',
                        'specifications' => '<ul><li>1단계 - 지하수 탱크（GWT）용량 1,000 m3.</li><li>총 42헥타르의 7개 저수지로 빗물 수집으로도 사용됩니다.</li></ul>',
                        'meta_title' => '수처리 플랜트 - JIIPE 항구',
                        'meta_description' => '1,000 m3 탱크와 7개의 42헥타르 저수지를 갖춘 수처리 플랜트',
                        'meta_keywords' => '수처리, 물탱크, 저수지, JIIPE',
                    ],
                    'tw' => [
                        'name' => '水處理廠',
                        'subtitle' => '工業供水',
                        'description' => '我們提供工業用水，配備最佳設備、系統和服務，以提高您的運營可靠性，降低生產成本並支持環境合規。',
                        'specifications' => '<ul><li>第1階段 - 地下水箱（GWT）容量1,000 m3。</li><li>7個蓄水池，總面積42公頃，也用作雨水收集。</li></ul>',
                        'meta_title' => '水處理廠 - JIIPE港口',
                        'meta_description' => '水處理廠配備1,000 m3水箱和7個42公頃蓄水池',
                        'meta_keywords' => '水處理, 水箱, 蓄水池, JIIPE',
                    ],
                ],
            ],
            [
                'id' => 6,
                'zone_id' => 6,
                'image' => null,
                'icon' => 'thumb_99681-waste-1_adaptiveResize_59_59.png',
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Pengolahan Air Limbah',
                        'subtitle' => 'Waste Water Treatment Plant',
                        'description' => 'Fasilitas pengolahan air limbah industri dengan sistem yang efisien.',
                        'specifications' => '<ul><li>FASE 1 - Pengolahan Air Limbah Industri (IPAL) dengan 2.500 m3 per hari.</li><li>Pipa pengumpul air limbah di Blok E.</li></ul>',
                        'meta_title' => 'Pengolahan Air Limbah - JIIPE Port',
                        'meta_description' => 'Pengolahan air limbah industri (IPAL) dengan kapasitas 2.500 m3 per hari',
                        'meta_keywords' => 'pengolahan air limbah, IPAL, waste water treatment, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Waste Water Treatment',
                        'subtitle' => 'Waste Water Treatment Plant',
                        'description' => 'Industrial waste water treatment facilities with efficient system.',
                        'specifications' => '<ul><li>PHASE 1 - Industrial Waste Water Treatment Plant (WWTP) with 2,500 m3 per day.</li><li>Waste water collection pipes in Block E.</li></ul>',
                        'meta_title' => 'Waste Water Treatment - JIIPE Port',
                        'meta_description' => 'Industrial waste water treatment plant (WWTP) with capacity 2,500 m3 per day',
                        'meta_keywords' => 'waste water treatment, WWTP, industrial wastewater, JIIPE',
                    ],
                    'zh' => [
                        'name' => '废水处理',
                        'subtitle' => '废水处理厂',
                        'description' => '工业废水处理设施，系统高效。',
                        'specifications' => '<ul><li>第1阶段 - 工业废水处理厂（WWTP），每天2,500 m3。</li><li>E区的废水收集管道。</li></ul>',
                        'meta_title' => '废水处理 - JIIPE港口',
                        'meta_description' => '工业废水处理厂（WWTP），容量每天2,500 m3',
                        'meta_keywords' => '废水处理, WWTP, 工业废水, JIIPE',
                    ],
                    'ja' => [
                        'name' => '廃水処理',
                        'subtitle' => '廃水処理プラント',
                        'description' => '効率的なシステムを備えた工業廃水処理施設。',
                        'specifications' => '<ul><li>フェーズ1 - 工業廃水処理プラント（WWTP），1日あたり2,500 m3。</li><li>ブロックEの廃水収集パイプ。</li></ul>',
                        'meta_title' => '廃水処理 - JIIPE港',
                        'meta_description' => '工業廃水処理プラント（WWTP），容量1日あたり2,500 m3',
                        'meta_keywords' => '廃水処理, WWTP, 工業廃水, JIIPE',
                    ],
                    'ko' => [
                        'name' => '폐수 처리',
                        'subtitle' => '폐수 처리 플랜트',
                        'description' => '효율적인 시스템을 갖춘 산업 폐수 처리 시설.',
                        'specifications' => '<ul><li>1단계 - 산업 폐수 처리 플랜트（WWTP），하루 2,500 m3.</li><li>E블록의 폐수 수집 파이프.</li></ul>',
                        'meta_title' => '폐수 처리 - JIIPE 항구',
                        'meta_description' => '산업 폐수 처리 플랜트（WWTP），용량 하루 2,500 m3',
                        'meta_keywords' => '폐수 처리, WWTP, 산업 폐수, JIIPE',
                    ],
                    'tw' => [
                        'name' => '廢水處理',
                        'subtitle' => '廢水處理廠',
                        'description' => '工業廢水處理設施，系統高效。',
                        'specifications' => '<ul><li>第1階段 - 工業廢水處理廠（WWTP），每天2,500 m3。</li><li>E區的廢水收集管道。</li></ul>',
                        'meta_title' => '廢水處理 - JIIPE港口',
                        'meta_description' => '工業廢水處理廠（WWTP），容量每天2,500 m3',
                        'meta_keywords' => '廢水處理, WWTP, 工業廢水, JIIPE',
                    ],
                ],
            ],
        ];

        // Data untuk Zone ID 7
        $energiesZone7 = [
            [
                'id' => 7,
                'zone_id' => 7,
                'image' => null,
                'icon' => 'thumb_cd9fd-power-plant_adaptiveResize_59_59.png',
                'order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Pembangkit Listrik',
                        'subtitle' => 'Pembangkit Listrik Tenaga Gas dan Batubara',
                        'description' => 'Pembangkit Listrik Tenaga Gas dan Batubara dengan sistem siklus gabungan, efektif dan fleksibel dengan emisi rendah dalam meminimalkan dampak lingkungan dan solusi optimal.',
                        'specifications' => '<ul><li><strong>Listrik</strong><br>FASE 1 - 3 x 7,65 MW DUAL FUEL POWER PLANT disediakan dan EPC oleh Wärtsilä, Finland. Terletak di Blok E.</li><li><strong>Gas</strong><br>FASE 1 - pipa gas di Blok E (6"), Daendels ke Underpass Road (16") dan dari Pipa PGN (24") di Jalan Daendels.</li></ul>',
                        'meta_title' => 'Pembangkit Listrik - GEM City JIIPE',
                        'meta_description' => 'Pembangkit listrik tenaga gas dan batubara dengan sistem siklus gabungan, 3 x 7,65 MW',
                        'meta_keywords' => 'pembangkit listrik, power plant, gas, batubara, GEM City, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Power Plant',
                        'subtitle' => 'Gas and Coal Power Plant',
                        'description' => 'Gas and Coal Power Plant with combined cycle system, effective and flexible with low emission in minimizing environmental impact and optimal solution.',
                        'specifications' => '<ul><li><strong>Electricity</strong><br>PHASE 1 - 3 x 7.65 MW DUAL FUEL POWER PLANT provided and EPC by Wärtsilä, Finland. Located in Block E.</li><li><strong>Gas</strong><br>PHASE 1 - gas pipe in Block E (6"), Daendels to Underpass Road (16") and from PGN Pipe (24") on Daendels Road.</li></ul>',
                        'meta_title' => 'Power Plant - GEM City JIIPE',
                        'meta_description' => 'Gas and coal power plant with combined cycle system, 3 x 7.65 MW',
                        'meta_keywords' => 'power plant, gas, coal, GEM City, JIIPE',
                    ],
                    'zh' => [
                        'name' => '发电厂',
                        'subtitle' => '燃气和煤炭发电厂',
                        'description' => '燃气和煤炭发电厂采用联合循环系统，高效灵活，低排放，最大限度地减少环境影响和优化解决方案。',
                        'specifications' => '<ul><li><strong>电力</strong><br>第1阶段 - 3 x 7.65 MW双燃料发电厂，由芬兰Wärtsilä提供和EPC。位于E区。</li><li><strong>燃气</strong><br>第1阶段 - E区燃气管道（6英寸），Daendels到地下通道（16英寸）和Daendels路上的PGN管道（24英寸）。</li></ul>',
                        'meta_title' => '发电厂 - GEM City JIIPE',
                        'meta_description' => '燃气和煤炭发电厂采用联合循环系统，3 x 7.65 MW',
                        'meta_keywords' => '发电厂, 燃气, 煤炭, GEM City, JIIPE',
                    ],
                    'ja' => [
                        'name' => '発電所',
                        'subtitle' => 'ガスおよび石炭発電所',
                        'description' => 'ガスおよび石炭発電所で、コンバインドサイクルシステムを備え、効果的で柔軟性があり、低排出で環境への影響を最小限に抑え、最適なソリューションを提供します。',
                        'specifications' => '<ul><li><strong>電力</strong><br>フェーズ1 - 3 x 7.65 MWデュアル燃料発電所、フィンランドのWärtsiläによって提供およびEPC。ブロックEに位置。</li><li><strong>ガス</strong><br>フェーズ1 - ブロックEのガスパイプ（6インチ），DaendelsからUnderpass Road（16インチ）およびDaendels RoadのPGNパイプ（24インチ）。</li></ul>',
                        'meta_title' => '発電所 - GEM City JIIPE',
                        'meta_description' => 'ガスおよび石炭発電所で、コンバインドサイクルシステムを備え、3 x 7.65 MW',
                        'meta_keywords' => '発電所, ガス, 石炭, GEM City, JIIPE',
                    ],
                    'ko' => [
                        'name' => '발전소',
                        'subtitle' => '가스 및 석탄 발전소',
                        'description' => '가스 및 석탄 발전소로 복합 사이클 시스템을 갖추고 있으며, 효과적이고 유연하며 저배출로 환경 영향을 최소화하고 최적의 솔루션을 제공합니다.',
                        'specifications' => '<ul><li><strong>전력</strong><br>1단계 - 3 x 7.65 MW 이중 연료 발전소, 핀란드 Wärtsilä에서 제공 및 EPC. E블록에 위치.</li><li><strong>가스</strong><br>1단계 - E블록의 가스 파이프（6인치），Daendels에서 지하도로（16인치）및 Daendels 도로의 PGN 파이프（24인치）.</li></ul>',
                        'meta_title' => '발전소 - GEM City JIIPE',
                        'meta_description' => '가스 및 석탄 발전소로 복합 사이클 시스템을 갖춤, 3 x 7.65 MW',
                        'meta_keywords' => '발전소, 가스, 석탄, GEM City, JIIPE',
                    ],
                    'tw' => [
                        'name' => '發電廠',
                        'subtitle' => '燃氣和煤炭發電廠',
                        'description' => '燃氣和煤炭發電廠採用聯合循環系統，高效靈活，低排放，最大限度地減少環境影響和優化解決方案。',
                        'specifications' => '<ul><li><strong>電力</strong><br>第1階段 - 3 x 7.65 MW雙燃料發電廠，由芬蘭Wärtsilä提供和EPC。位於E區。</li><li><strong>燃氣</strong><br>第1階段 - E區燃氣管道（6英寸），Daendels到地下通道（16英寸）和Daendels路上的PGN管道（24英寸）。</li></ul>',
                        'meta_title' => '發電廠 - GEM City JIIPE',
                        'meta_description' => '燃氣和煤炭發電廠採用聯合循環系統，3 x 7.65 MW',
                        'meta_keywords' => '發電廠, 燃氣, 煤炭, GEM City, JIIPE',
                    ],
                ],
            ],
            [
                'id' => 8,
                'zone_id' => 7,
                'image' => null,
                'icon' => 'thumb_6817c-water-1_adaptiveResize_59_59.png',
                'order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Instalasi Pengolahan Air',
                        'subtitle' => 'Water Treatment Plant',
                        'description' => 'Kami menyediakan air industri dengan peralatan, sistem, dan layanan terbaik untuk meningkatkan keandalan operasional Anda, mengurangi biaya produksi Anda dan mendukung kepatuhan lingkungan.',
                        'specifications' => '<ul><li>FASE 1 - Tangki Air Tanah (GWT) kapasitas 1.000 m3.</li><li>7 kolam penampungan air dengan total 42 ha juga sebagai pengumpulan air hujan.</li></ul>',
                        'meta_title' => 'Instalasi Pengolahan Air - GEM City JIIPE',
                        'meta_description' => 'Instalasi pengolahan air dengan tangki 1.000 m3 dan 7 kolam penampungan 42 ha',
                        'meta_keywords' => 'pengolahan air, water treatment, GEM City, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Water Treatment Plant',
                        'subtitle' => 'Industrial Water Supply',
                        'description' => 'We supply industrial water with best equipment, system, and service to improve your operational reliability, reduce your production cost and support environmental compliance.',
                        'specifications' => '<ul><li>PHASE 1 - Ground Water Tank (GWT) capacity 1,000 m3.</li><li>7 water retention ponds with a total of 42 ha also as rainwater collection.</li></ul>',
                        'meta_title' => 'Water Treatment Plant - GEM City JIIPE',
                        'meta_description' => 'Water treatment plant with 1,000 m3 tank and 7 retention ponds 42 ha',
                        'meta_keywords' => 'water treatment, GEM City, JIIPE',
                    ],
                    'zh' => [
                        'name' => '水处理厂',
                        'subtitle' => '工业供水',
                        'description' => '我们提供工业用水，配备最佳设备、系统和服务，以提高您的运营可靠性，降低生产成本并支持环境合规。',
                        'specifications' => '<ul><li>第1阶段 - 地下水箱（GWT）容量1,000 m3。</li><li>7个蓄水池，总面积42公顷，也用作雨水收集。</li></ul>',
                        'meta_title' => '水处理厂 - GEM City JIIPE',
                        'meta_description' => '水处理厂配备1,000 m3水箱和7个42公顷蓄水池',
                        'meta_keywords' => '水处理, GEM City, JIIPE',
                    ],
                    'ja' => [
                        'name' => '水処理プラント',
                        'subtitle' => '工業用水供給',
                        'description' => '最高の機器、システム、サービスを備えた工業用水を供給し、運用の信頼性を向上させ、生産コストを削減し、環境コンプライアンスをサポートします。',
                        'specifications' => '<ul><li>フェーズ1 - 地下水タンク（GWT）容量1,000 m3。</li><li>合計42ヘクタールの7つの貯水池で、雨水収集としても機能。</li></ul>',
                        'meta_title' => '水処理プラント - GEM City JIIPE',
                        'meta_description' => '1,000 m3タンクと7つの42ヘクタール貯水池を備えた水処理プラント',
                        'meta_keywords' => '水処理, GEM City, JIIPE',
                    ],
                    'ko' => [
                        'name' => '수처리 플랜트',
                        'subtitle' => '산업용수 공급',
                        'description' => '최고의 장비, 시스템 및 서비스를 갖춘 산업용수를 공급하여 운영 신뢰성을 향상시키고 생산 비용을 절감하며 환경 규정 준수를 지원합니다.',
                        'specifications' => '<ul><li>1단계 - 지하수 탱크（GWT）용량 1,000 m3.</li><li>총 42헥타르의 7개 저수지로 빗물 수집으로도 사용됩니다.</li></ul>',
                        'meta_title' => '수처리 플랜트 - GEM City JIIPE',
                        'meta_description' => '1,000 m3 탱크와 7개의 42헥타르 저수지를 갖춘 수처리 플랜트',
                        'meta_keywords' => '수처리, GEM City, JIIPE',
                    ],
                    'tw' => [
                        'name' => '水處理廠',
                        'subtitle' => '工業供水',
                        'description' => '我們提供工業用水，配備最佳設備、系統和服務，以提高您的運營可靠性，降低生產成本並支持環境合規。',
                        'specifications' => '<ul><li>第1階段 - 地下水箱（GWT）容量1,000 m3。</li><li>7個蓄水池，總面積42公頃，也用作雨水收集。</li></ul>',
                        'meta_title' => '水處理廠 - GEM City JIIPE',
                        'meta_description' => '水處理廠配備1,000 m3水箱和7個42公頃蓄水池',
                        'meta_keywords' => '水處理, GEM City, JIIPE',
                    ],
                ],
            ],
            [
                'id' => 9,
                'zone_id' => 7,
                'image' => null,
                'icon' => 'thumb_f01d1-waste_adaptiveResize_59_59.png',
                'order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
                'translations' => [
                    'id' => [
                        'name' => 'Pengolahan Air Limbah',
                        'subtitle' => 'Waste Water Treatment Plant',
                        'description' => 'Fasilitas pengolahan air limbah industri dengan sistem yang efisien.',
                        'specifications' => '<ul><li>FASE 1 - Pengolahan Air Limbah Industri (IPAL) dengan 2.500 m3 per hari.</li><li>Pipa pengumpul air limbah di Blok E.</li></ul>',
                        'meta_title' => 'Pengolahan Air Limbah - GEM City JIIPE',
                        'meta_description' => 'Pengolahan air limbah industri (IPAL) dengan kapasitas 2.500 m3 per hari',
                        'meta_keywords' => 'pengolahan air limbah, IPAL, GEM City, JIIPE',
                    ],
                    'en' => [
                        'name' => 'Waste Water Treatment',
                        'subtitle' => 'Waste Water Treatment Plant',
                        'description' => 'Industrial waste water treatment facilities with efficient system.',
                        'specifications' => '<ul><li>PHASE 1 - Industrial Waste Water Treatment Plant (WWTP) with 2,500 m3 per day.</li><li>Waste water collection pipes in Block E.</li></ul>',
                        'meta_title' => 'Waste Water Treatment - GEM City JIIPE',
                        'meta_description' => 'Industrial waste water treatment plant (WWTP) with capacity 2,500 m3 per day',
                        'meta_keywords' => 'waste water treatment, WWTP, GEM City, JIIPE',
                    ],
                    'zh' => [
                        'name' => '废水处理',
                        'subtitle' => '废水处理厂',
                        'description' => '工业废水处理设施，系统高效。',
                        'specifications' => '<ul><li>第1阶段 - 工业废水处理厂（WWTP），每天2,500 m3。</li><li>E区的废水收集管道。</li></ul>',
                        'meta_title' => '废水处理 - GEM City JIIPE',
                        'meta_description' => '工业废水处理厂（WWTP），容量每天2,500 m3',
                        'meta_keywords' => '废水处理, WWTP, GEM City, JIIPE',
                    ],
                    'ja' => [
                        'name' => '廃水処理',
                        'subtitle' => '廃水処理プラント',
                        'description' => '効率的なシステムを備えた工業廃水処理施設。',
                        'specifications' => '<ul><li>フェーズ1 - 工業廃水処理プラント（WWTP），1日あたり2,500 m3。</li><li>ブロックEの廃水収集パイプ。</li></ul>',
                        'meta_title' => '廃水処理 - GEM City JIIPE',
                        'meta_description' => '工業廃水処理プラント（WWTP），容量1日あたり2,500 m3',
                        'meta_keywords' => '廃水処理, WWTP, GEM City, JIIPE',
                    ],
                    'ko' => [
                        'name' => '폐수 처리',
                        'subtitle' => '폐수 처리 플랜트',
                        'description' => '효율적인 시스템을 갖춘 산업 폐수 처리 시설.',
                        'specifications' => '<ul><li>1단계 - 산업 폐수 처리 플랜트（WWTP），하루 2,500 m3.</li><li>E블록의 폐수 수집 파이프.</li></ul>',
                        'meta_title' => '폐수 처리 - GEM City JIIPE',
                        'meta_description' => '산업 폐수 처리 플랜트（WWTP），용량 하루 2,500 m3',
                        'meta_keywords' => '폐수 처리, WWTP, GEM City, JIIPE',
                    ],
                    'tw' => [
                        'name' => '廢水處理',
                        'subtitle' => '廢水處理廠',
                        'description' => '工業廢水處理設施，系統高效。',
                        'specifications' => '<ul><li>第1階段 - 工業廢水處理廠（WWTP），每天2,500 m3。</li><li>E區的廢水收集管道。</li></ul>',
                        'meta_title' => '廢水處理 - GEM City JIIPE',
                        'meta_description' => '工業廢水處理廠（WWTP），容量每天2,500 m3',
                        'meta_keywords' => '廢水處理, WWTP, GEM City, JIIPE',
                    ],
                ],
            ],
        ];

        // Gabungkan semua data
        $allEnergies = array_merge($energiesZone5, $energiesZone6, $energiesZone7);

        // Insert data
        foreach ($allEnergies as $energy) {
            $translations = $energy['translations'];
            unset($energy['translations']);

            // Insert energy
            DB::table('sub_resource_energies')->insert($energy);

            // Insert translations
            foreach ($translations as $locale => $translation) {
                DB::table('sub_resource_energy_translations')->insert([
                    'sub_resource_energy_id' => $energy['id'],
                    'locale' => $locale,
                    'name' => $translation['name'],
                    'subtitle' => $translation['subtitle'] ?? null,
                    'description' => $translation['description'],
                    'specifications' => $translation['specifications'] ?? null,
                    'meta_title' => $translation['meta_title'] ?? null,
                    'meta_description' => $translation['meta_description'] ?? null,
                    'meta_keywords' => $translation['meta_keywords'] ?? null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }
    }
}
