@include('layouts.admin.home.js.slider_js')
@include('layouts.admin.zone.zone_js')
@include('layouts.admin.home.js.tenant_js')
@include('layouts.admin.home.js.review_js')
@include('layouts.admin.home.js.faq_js')
